url_sbis = "https://sbis.ru/"
url_sbis_contacts = "https://sbis.ru/contacts"
url_tensor = "https://tensor.ru/"
url_tensor_about = "https://tensor.ru/about"
url_sbis_download = "https://sbis.ru/download"