URL_SBIS = "https://sbis.ru/"
URL_SBIS_CONTACTS = "https://sbis.ru/contacts"
URL_TENSOR = "https://tensor.ru/"
URL_TENSOR_ABOUT = "https://tensor.ru/about"
URL_SBIS_DOWNLOAD = "https://sbis.ru/download"